# Generated by Django 4.2.3 on 2023-08-19 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                ("title", models.CharField(max_length=50)),
                (
                    "isFeaturedConstruction",
                    models.BooleanField(
                        default=False, verbose_name="Featured Construction"
                    ),
                ),
                ("dateCreated", models.DateField(auto_now_add=True)),
                ("isComplete", models.BooleanField(default=False)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                ("pricePerMonth", models.FloatField(default=0, verbose_name="Price")),
                (
                    "isLate",
                    models.BooleanField(default=False, verbose_name="Rent is Late"),
                ),
                ("lateFee", models.FloatField(default=0, verbose_name="Late Fee")),
                ("startDate", models.DateField(verbose_name="Lease Start Date")),
                ("dueDate", models.DateField(verbose_name="Rent Due Date")),
                (
                    "endDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Lease End Date"
                    ),
                ),
                (
                    "monthsLeft",
                    models.IntegerField(
                        default=0, verbose_name="Months Remaining on Lease"
                    ),
                ),
                (
                    "currentBalance",
                    models.FloatField(default=0, verbose_name="Balance"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                ("address", models.CharField(max_length=50)),
                (
                    "city",
                    models.TextField(
                        choices=[
                            ("Oxford", "Oxford"),
                            ("Tupelo", "Tupelo"),
                            ("Saltillo", "Saltillo"),
                            ("Baldwyn", "Baldwyn"),
                            ("West Point", "West Point"),
                            ("Booneville", "Booneville"),
                            ("Guntown", "Guntown"),
                            ("Amory", "Amory"),
                            ("New Albany", "New Albany"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "isRented",
                    models.BooleanField(default=False, verbose_name="Occupied"),
                ),
                ("price", models.FloatField(verbose_name="Price")),
                ("squareFoot", models.IntegerField(verbose_name="Square Footage")),
                ("bedrooms", models.IntegerField(verbose_name="Bedrooms")),
                ("bathrooms", models.FloatField(verbose_name="Bathrooms")),
                ("isPetFriendly", models.BooleanField(verbose_name="Pet Friendly")),
                (
                    "isFeaturedProperty",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("userEmail", models.EmailField(max_length=254, verbose_name="Email")),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                (
                    "linkToBuiltinUser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linkToLease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.lease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_bool", models.BooleanField(default=False)),
                ("stripe_checkout_id", models.CharField(max_length=500)),
                ("payment_amount", models.FloatField(default=0)),
                ("dateCreated", models.DateField(auto_now_add=True)),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.tenant"
                    ),
                ),
                (
                    "linked_lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.lease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="images/")),
                (
                    "propertyOfImage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.rentalproperty",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lease",
            name="linkToProperty",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.rentalproperty",
                verbose_name="Address",
            ),
        ),
        migrations.CreateModel(
            name="ConstructionJobPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="images/")),
                (
                    "constructionOfImage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.constructionjob",
                    ),
                ),
            ],
        ),
    ]
