# Generated by Django 4.2.3 on 2023-07-19 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_rename_user_profile_person"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Tenant",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="person",
            new_name="linkToBuiltinUser",
        ),
    ]
