# Generated by Django 4.2.3 on 2023-07-21 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_profile_tenant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=50)),
                ("isRented", models.BooleanField(default=False)),
                ("pricePerMonth", models.FloatField()),
                ("squareFoot", models.IntegerField()),
                ("numOfBedrooms", models.IntegerField()),
                ("numOfBathrooms", models.FloatField()),
                ("isPetFriendly", models.BooleanField()),
                ("picture", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
                (
                    "linkToTenant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.tenant",
                    ),
                ),
            ],
        ),
    ]
