# Generated by Django 4.2.3 on 2023-07-22 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_remove_rentalproperty_linktotenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="linkToBuiltinUser",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
