# Generated by Django 4.2.3 on 2023-07-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_tenant_linktobuiltinuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyphoto",
            name="property",
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="propertyOfImage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.rentalproperty",
            ),
        ),
    ]
