# Generated by Django 4.2.3 on 2023-07-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rentalproperty_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="city",
            field=models.TextField(
                choices=[
                    ("Oxford", "Oxford"),
                    ("Tupelo", "Tupelo"),
                    ("Saltillo", "Saltillo"),
                    ("Baldwyn", "Baldwyn"),
                    ("West Point", "West Point"),
                    ("Booneville", "Booneville"),
                    ("Guntown", "Guntown"),
                    ("Amory", "Amory"),
                    ("New Albany", "New Albany"),
                ],
                null=True,
            ),
        ),
    ]
