# Generated by Django 4.2.3 on 2023-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_rentalproperty_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="userEmail",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
