# Generated by Django 4.2.3 on 2023-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_tenant_useremail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="isPetFriendly",
            field=models.BooleanField(verbose_name="Pet Friendly"),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="isRented",
            field=models.BooleanField(default=False, verbose_name="Available"),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="numOfBathrooms",
            field=models.FloatField(verbose_name="Bathrooms"),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="numOfBedrooms",
            field=models.IntegerField(verbose_name="Bedrooms"),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="pricePerMonth",
            field=models.FloatField(verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="squareFoot",
            field=models.IntegerField(verbose_name="Square Footage"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="currentBalance",
            field=models.IntegerField(default=0, verbose_name="Balance"),
        ),
    ]
