# Generated by Django 4.2.3 on 2023-07-26 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_rentalproperty_ispetfriendly_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("dateCreated", models.DateField(auto_now_add=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="isRented",
            field=models.BooleanField(default=False, verbose_name="Occupied"),
        ),
        migrations.CreateModel(
            name="ConstructionTicketPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="images/")),
                (
                    "ConstructionOfImage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.constructionticket",
                    ),
                ),
            ],
        ),
    ]
