# Generated by Django 4.2.3 on 2023-08-02 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_constructionticket_alter_rentalproperty_isrented_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="isFeaturedProperty",
            field=models.BooleanField(default=False, verbose_name="Featured"),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="propertyOfImage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.rentalproperty",
            ),
        ),
    ]
