# Generated by Django 4.2.3 on 2023-08-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rentalproperty_isfeaturedproperty_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentalproperty",
            old_name="numOfBathrooms",
            new_name="bathrooms",
        ),
        migrations.RenameField(
            model_name="rentalproperty",
            old_name="numOfBedrooms",
            new_name="bedrooms",
        ),
        migrations.RenameField(
            model_name="rentalproperty",
            old_name="pricePerMonth",
            new_name="price",
        ),
        migrations.CreateModel(
            name="TenantPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_bool", models.BooleanField(default=False)),
                ("stripe_checkout_id", models.CharField(max_length=500)),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.tenant"
                    ),
                ),
            ],
        ),
    ]
