# Generated by Django 4.2.3 on 2023-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_rename_numofbathrooms_rentalproperty_bathrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionticket",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalproperty",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
