# Generated by Django 4.2.3 on 2023-08-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_constructionjob_constructionjobphoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="numOfMonths",
            field=models.IntegerField(default=12),
        ),
    ]
