# Generated by Django 4.2.3 on 2023-08-15 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_lease_numofmonths"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lease",
            name="dateCreated",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="numOfMonths",
        ),
        migrations.AddField(
            model_name="lease",
            name="dueDate",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Rent Due Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lease",
            name="endDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Lease End Date"
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="startDate",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Lease Start Date"
            ),
            preserve_default=False,
        ),
    ]
