# Generated by Django 4.2.3 on 2023-08-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_lease_datecreated_remove_lease_numofmonths_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="isLate",
            field=models.BooleanField(default=False, verbose_name="Rent is Late"),
        ),
        migrations.AddField(
            model_name="lease",
            name="lateFee",
            field=models.FloatField(default=0, verbose_name="Late Fee"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="linkToProperty",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.rentalproperty",
                verbose_name="Address",
            ),
        ),
    ]
