# Generated by Django 4.2.3 on 2023-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_lease_islate_lease_latefee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="monthsLeft",
            field=models.IntegerField(
                default=12, verbose_name="Months Remaining on Lease"
            ),
            preserve_default=False,
        ),
    ]
