# Generated by Django 4.2.3 on 2023-08-15 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_lease_monthsleft"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantpayment",
            name="dateCreated",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
