# Generated by Django 4.2.3 on 2023-08-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_tenant_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="monthsLeft",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Months Remaining on Lease"
            ),
        ),
    ]
